version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: user-microservice-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: howpathetic1
      MYSQL_DATABASE: user-microservice
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: user-microservice-phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: "howpathetic1"  
    depends_on:
      - db

volumes:
  db_data: